name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VERSION: '0-ea+${{ github.run_number }}'

jobs:
  build:
    name: 'Build with Java ${{ matrix.java }} on ${{ runner.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest , macOS-latest, windows-latest ]
        java: [ 16 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Set up JDK'
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: 'Build with Bach'
        uses: sormuras/bach-build@v1
        with:
          bach-arguments: --project-version ${{ env.VERSION }} build
      - name: 'Upload build artifact'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ env.VERSION }}-${{ runner.os }}
          path: |
            .gitignore
            .bach/workspace/logbook.md
            .bach/workspace/modules
